name: proyecto_eventos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  syncfusion_flutter_charts: ^28.1.33

  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.0 # Para subir fotos de perfil
  
  # Utilidades
  intl: ^0.20.0             # Para fechas en español
  image_picker: ^1.1.2      # Para seleccionar foto de galería
  
  # QR (Estudiante y Organizador)
  qr_flutter: ^4.1.0        # Generar QR (Estudiante)
  mobile_scanner: ^5.2.0    # Leer QR (Organizador) - Nota: Versiones 7.x cambian la API
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: "^2.3.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icono_app.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#010314"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  # Color de fondo que llenará toda la pantalla
  color: "#010314" 
  
  # Tu logo centrado (Android lo mostrará en el centro sin recortarlo si tiene márgenes)
  image: "assets/images/icono_app.png"

  # Configuración específica para Android 12+
  android_12:
    image: "assets/images/icono_app.png"
    color: "#010314"
    # Esto evita que el logo ocupe todo el círculo y se recorte
    icon_background_color: "#010314" 

  # OPCIONAL: Para Androids viejos (menores a 12) que SÍ soportan imagen completa
  # Aquí sí puedes poner tu imagen rectangular original si quieres
  background_image: "assets/images/splash_logo.jpg"